name: simple_mvp
version: 0.3.0
description: >
  SimpleMVP is a framework for writing single-page applications in Dart.
author: Victor Savkin <vic.savkin@gmail.com>
homepage: https://github.com/vsavkin/SimpleMVP
dependencies:
  unittest: 0.2.8+2
